// Generated by Claude. Verify against code. May be stale.
//
// Type declarations for fetch-multipart.js. Hand-maintained alongside
// the implementation.

export class MultipartParseError extends TypeError {
  constructor(message: string)
  readonly name: 'MultipartParseError'
}

export class MultipartParser {
  constructor(boundary: string)
  readonly boundary: string
  write(chunk: Uint8Array, onPart?: ((part: BodyPart) => void) | null): void
  finish(): void
}

export class BodyPart {
  readonly headers: Headers
  readonly body: ReadableStream<Uint8Array>
  readonly bodyUsed: boolean
  bytes(): Promise<Uint8Array>
  arrayBuffer(): Promise<ArrayBuffer>
  text(): Promise<string>
  json(): Promise<any>
  blob(): Promise<Blob>
  parts(): AsyncGenerator<BodyPart, void, unknown>
}

export function getMultipartBoundary(contentType: string): string | null

export interface ContentDispositionParts {
  type: string | null
  name: string | null
  filename: string | null
}

export function parseContentDisposition(header: string | null): ContentDispositionParts

declare global {
  interface Response {
    parts(): AsyncGenerator<BodyPart, void, unknown>
  }
}
